uploads = []
generated = []

[[outputs]]
id = "bn0Rw0skVnTQF8LEQyPXu"
uri = "file://TEACHER_MODULE_DOCUMENTATION.md"
type = "text"
title = "Teacher Module — Dev Log"

[[outputs]]
id = "DLxfPDiSCnRSjXMdHq15q"
uri = "file://TEACHER_MODULE_DEFENSE.md"
type = "text"
title = "Teacher Module — Defense Script"
