// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7j5CxvmUw4GDAHQx6HZEtuuqfIQ9JMc',
    appId: '1:214833614255:web:861250a32e6e4228e6335a',
    messagingSenderId: '214833614255',
    projectId: 'education-edc0e',
    authDomain: 'education-edc0e.firebaseapp.com',
    storageBucket: 'education-edc0e.firebasestorage.app',
    measurementId: 'G-JM7VBKHCSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdBaQztshwdbXvAJ0TQO1W1LaFE7UgKhQ',
    appId: '1:214833614255:android:75f28cefff7331d3e6335a',
    messagingSenderId: '214833614255',
    projectId: 'education-edc0e',
    storageBucket: 'education-edc0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9C3SFPDtftIeZ1ZKAGZe4DfDGhNWssE0',
    appId: '1:214833614255:ios:7af21b043545184fe6335a',
    messagingSenderId: '214833614255',
    projectId: 'education-edc0e',
    storageBucket: 'education-edc0e.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9C3SFPDtftIeZ1ZKAGZe4DfDGhNWssE0',
    appId: '1:214833614255:ios:7af21b043545184fe6335a',
    messagingSenderId: '214833614255',
    projectId: 'education-edc0e',
    storageBucket: 'education-edc0e.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK7j5CxvmUw4GDAHQx6HZEtuuqfIQ9JMc',
    appId: '1:214833614255:web:5f28c072fe877ff6e6335a',
    messagingSenderId: '214833614255',
    projectId: 'education-edc0e',
    authDomain: 'education-edc0e.firebaseapp.com',
    storageBucket: 'education-edc0e.firebasestorage.app',
    measurementId: 'G-KXH8DHY6NR',
  );
}
